version: '3.3'
services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3036"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
